---

- name: Packman repos
  become: "yes"
  zypper_repository:
    repo: "{{ item.uri }}"
    name: "{{ item.name }}"
    auto_import_keys: "yes"
  with_items: "{{ repos }}"

- name: Upgrade with Vendor Change
  become: "yes"
  zypper:
    name: "*"
    state: dist-upgrade
    extra_args: "--no-allow-vendor-change"

- name: gstreamer-plugins-libav is installed
  become: "yes"
  zypper:
    name: "gstreamer-plugins-libav"
