---

- name: Gnome Shell Extension Tool
  become: "yes"
  zypper:
    name: gnome-shell-devel
    state: latest

- name: Python3 gobject
  become: "yes"
  zypper:
    name: python3-gobject
    state: latest

- name: System Monitor Extension Dependencies
  become: "yes"
  zypper:
    name: "{{ item }}"
  with_items:
    - libgtop-devel
    - NetworkManager-devel

- name: Github Gnome Shell Extensions
  shell_extension:
    uri: "https://github.com/{{ item.uri }}.git"
    name: "{{ item.name }}"
    state: enabled
    subfolder: "{{ item.subfolder }}"
  with_items:
    - uri: "paradoxxxzero/gnome-shell-system-monitor-applet"
      name: "system-monitor@paradoxxx.zero.gmail.com"
      subfolder: "system-monitor@paradoxxx.zero.gmail.com"

    - uri: "phocean/TopIcons-Plus"
      name: "TopIcons@phocean.net"
      subfolder: ""

    - uri: "deadalnix/pixel-saver"
      name: "pixel-saver@deadalnix.me"
      subfolder: "pixel-saver@deadalnix.me"
