- name: Gnome Shell Extension Tool
  become: yes
  zypper:
    name: gnome-shell-devel

- name: System Monitor Extension Dependencies
  become: yes
  zypper:
    name: "{{ item }}"
  with_items:
    - libgtop-devel
    - NetworkManager-devel

- name: Github Gnome Shell Extensions
  shell_extension:
    uri: "https://github.com/MichaelAquilina/{{ item.uri }}.git"
    name: "{{ item.name }}"
    state: enabled
    subfolder: "{{ item.subfolder }}"
  with_items:
    - {uri: "gse-refresh-wifi", name: "refresh-wifi@kgshank.net", subfolder: "refresh-wifi@kgshank.net"}
    - {uri: "gnome-shell-system-monitor-applet", name: "system-monitor@paradoxxx.zero.gmail.com", subfolder: "system-monitor@paradoxxx.zero.gmail.com"}
    - {uri: "pixel-saver", name: "pixel-saver@deadalnix.me", subfolder: "pixel-saver@deadalnix.me"}
    - {uri: "gnome-shell-extension-stealmyfocus", name: "steal-my-focus@kagesenshi.org", subfolder: ""}
    - {uri: "topicons", name: "topIcons@kevinboxhoorn.yahoo.com", subfolder: ""}
    - {uri: "nohotcorner", name: "nohotcorner@azuri.free.fr", subfolder: ""}
    - {uri: "status-title-bar", name: "StatusTitleBar@devpower.org", subfolder: "src"}
    - {uri: "gnome-shell-extension-bettervolume", name: "bettervolume@tudmotu.com", subfolder: ""}
