---

- name: Gnome Shell Extension Tool
  become: "yes"
  zypper:
    name: gnome-shell-devel
    state: latest

- name: Python3 gobject
  become: "yes"
  zypper:
    name: python3-gobject
    state: latest

- name: System Monitor Extension Dependencies
  become: "yes"
  zypper:
    name: "{{ item }}"
  with_items:
    - libgtop-devel
    - NetworkManager-devel

- name: Github Gnome Shell Extensions
  shell_extension:
    uri: "https://github.com/{{ item.uri }}.git"
    name: "{{ item.name }}"
    state: enabled
    subfolder: "{{ item.subfolder }}"
  with_items:
    - uri: "MichaelAquilina/gse-refresh-wifi"
      name: "refresh-wifi@kgshank.net"
      subfolder: "refresh-wifi@kgshank.net"

    - uri: "MichaelAquilina/gnome-shell-system-monitor-applet"
      name: "system-monitor@paradoxxx.zero.gmail.com"
      subfolder: "system-monitor@paradoxxx.zero.gmail.com"

    - uri: "franglais125/no-title-bar"
      name: "no-title-bar@franglais125.gmail.com"
      subfolder: ""

    - uri: "MichaelAquilina/gnome-shell-extension-stealmyfocus"
      name: "steal-my-focus@kagesenshi.org"
      subfolder: ""

    - uri: "MichaelAquilina/TopIcons-Plus"
      name: "TopIcons@phocean.net"
      subfolder: ""

    - uri: "MichaelAquilina/nohotcorner"
      name: "nohotcorner@azuri.free.fr"
      subfolder: ""

    - uri: "MichaelAquilina/status-title-bar"
      name: "StatusTitleBar@devpower.org"
      subfolder: "src"
