---

sudo: false
dist: trusty

language: python
addons:
  apt:
    packages:
      - libyaml-dev

services:
  - docker

install:
  - pip install yamllint

before_script:
  - yamllint .

script:
  - docker build .
