---
- hosts: 127.0.0.1
  connection: local
  pre_tasks:
    - name: "Docker Container Status"
      stat:
        path: "/.dockerenv"
      register: dockerenv

  roles:
    - cli
    - docker
    - nvim
    - git
    - development
    - gnomeshell
    - gnomeshell-theme
    - gnomeshell-apps
    - gnomeshell-extensions
    - flatpak
    - mozilla
    - packman
    - nightlight
    - power
