---
- hosts: 127.0.0.1
  connection: local
  pre_tasks:
    - name: "Docker Container Status"
      stat:
        path: "/.dockerenv"
      register: dockerenv

  roles:
    - git
    - cli
    - nvim
    - core
    - gnome
    - gnomeshell-theme
    - flatpak
