---
- hosts: 127.0.0.1
  connection: local
  roles:
    - cli
    - cron
    - vim
    - git
    - development
    - gnomeshell
    - gnomeshell-theme
    - gnomeshell-extensions
    - gnomeshell-apps
    - nightlight
    - power
    - atom
