---
- hosts: 127.0.0.1
  connection: local
  roles:
    - cli
    - docker
    - nvim
    - git
    - development
    - gnomeshell
    - gnomeshell-theme
    - gnomeshell-apps
    - gnomeshell-extensions
    - flatpak
    - mozilla
    - packman
    - nightlight
    - power
