---

version: 2

jobs:
  run_playbook:
    docker:
      - image: "fedora:42"
    steps:
      - checkout
      - run:
          name: Install Expected Base Packages
          command: >
            dnf install -y ansible ansible-collection-community-general
            dbus-daemon
      - run:
          name: Run playbook
          command: ansible-playbook setup.yml

workflows:
  version: 2
  monthly_test:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - run_playbook
  playbook_test:
    jobs:
      - run_playbook
