# Required for some fallback icons on other themes
- name: Default Gnome Icon Theme is Ignored
  become: yes
  zypper:
    name: gnome-icon-theme
    state: latest

- name: Arc Theme is Installed
  become: yes
  zypper:
    name: gtk3-metatheme-arc
    state: latest

- name: Use Arc Theme
  gsettings:
    schema: org.gnome.desktop.interface
    key: gtk-theme
    value: "Arc-Darker"
