---

# Required for some fallback icons on other themes
- name: Default Gnome Icon Theme is Ignored
  become: "yes"
  zypper:
    name: gnome-icon-theme
    state: latest

- name: Arc Theme is Installed
  become: "yes"
  zypper:
    name: "{{ item }}"
    state: latest
  with_items:
    - gtk3-metatheme-arc
    - gtk2-metatheme-arc

- name: Use Arc Theme
  gsettings:
    schema: org.gnome.desktop.interface
    key: gtk-theme
    value: "Arc-Darker"

- name: Global Dark Theme is enabled
  ini_file:
    path: ~/.config/gtk-3.0/settings.ini
    section: Settings
    option: gtk-application-prefer-dark-theme
    value: "1"
