---

# Required for some fallback icons on other themes
- name: Default Gnome Icon Theme is Ignored
  become: "yes"
  package:
    name: gnome-icon-theme
    state: latest

- name: Arc Theme is Installed
  become: "yes"
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - arc-theme

- name: Set dark color schema
  dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

- name: Use Arc Theme
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Arc-Darker'"

- name: Global Dark Theme is enabled
  ini_file:
    path: ~/.config/gtk-3.0/settings.ini
    section: Settings
    option: gtk-application-prefer-dark-theme
    value: "1"
