---

- name: psutil is installed
  pip:
    name: psutil

- name: set number of workspaces
  dconf:
    key: "/org/gnome/desktop/wm/preferences/num-workspaces"
    value: "10"

- name: disable hot corners
  dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "false"

- name: resize with windows right-click
  dconf:
    key: "/org/gnome/desktop/wm/preferences/resize-with-right-button"
    value: "true"

- name: center new windows
  dconf:
    key: /org/gnome/mutter/center-new-windows
    value: "true"

- name: show battery percentage
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: set media keys
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/{{ item.action }}"
    value: "{{ item.key }}"
  with_items:
    - { action: "play", key: "['<Super>F6']" }
    - { action: "previous", key: "['<Super>F5']" }
    - { action: "next", key: "['<Super>F7']" }


- name: set custom key-bindings list
  dconf:
    key: "{{ custom_keybindings_path }}"
    value: "['{{ custom_keybindings_path}}/custom0/', '{{ custom_keybindings_path}}/custom1/']"

- name: set kitty key-bindings
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/{{ item.key }}"
    value: "'{{ item.value }}'"
  with_items:
    - { key: "binding", value: "<Alt>Return" }
    - { key: "name", value: "kitty" }
    - { key: "command", value: "kitty" }

- name: set ulauncher key-bindings
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/{{ item.key }}"
    value: "'{{ item.value }}'"
  with_items:
    - { key: "binding", value: "<Ctrl>Space" }
    - { key: "name", value: "ulauncher" }
    - { key: "command", value: "ulauncher-toggle" }



- name: Unset switch to application shortcuts
  dconf:
    key: "/org/gnome/shell/keybindings/switch-to-application-{{ item }}"
    value:  "['']"
  with_items:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 0

- name: disable mutter overlap key
  dconf:
    key: /org/gnome/mutter/overlay-key
    value: "''"

- name: Setup workspace switching shortcuts
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-{{ item.workspace }}"
    value:  "['<Super>{{ item.key }}']"
  with_items:
    - { workspace: 1, key: 1 }
    - { workspace: 2, key: 2 }
    - { workspace: 3, key: 3 }
    - { workspace: 4, key: 4 }
    - { workspace: 5, key: 5 }
    - { workspace: 6, key: 6 }
    - { workspace: 7, key: 7 }
    - { workspace: 8, key: 8 }
    - { workspace: 9, key: 9 }
    - { workspace: 10, key: 0 }

- name: Setup workspace moving shortcuts
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-{{ item.workspace }}"
    value:  "['<Shift><Super>{{ item.key }}']"
  with_items:
    - { workspace: 1, key: 1 }
    - { workspace: 2, key: 2 }
    - { workspace: 3, key: 3 }
    - { workspace: 4, key: 4 }
    - { workspace: 5, key: 5 }
    - { workspace: 6, key: 6 }
    - { workspace: 7, key: 7 }
    - { workspace: 8, key: 8 }
    - { workspace: 9, key: 9 }
    - { workspace: 10, key: 0 }
