---

- name: git is installed
  become: "yes"
  package:
    name: git

- name: rebase on pull
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: 'true'

- name: autostash on rebase
  community.general.git_config:
    name: rebase.autostash
    scope: global
    value: 'true'

- name: color ui is enabled
  community.general.git_config:
    name: color.ui
    scope: global
    value: 'true'

- name: simple push
  community.general.git_config:
    name: push.default
    scope: global
    value: simple

- name: dont prompt mergetool
  community.general.git_config:
    name: mergetool.prompt
    scope: global
    value: "false"

- name: dont prompt difftool
  community.general.git_config:
    name: difftool.prompt
    scope: global
    value: "false"

- name: global aliases
  community.general.git_config:
    name: alias.{{ item.alias }}
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { alias: cp, value: cherry-pick }
    - { alias: pushf, value: push --force-with-lease }

- name: global git ignore file
  community.general.git_config:
    name: core.excludesfile
    scope: global
    value: "{{ ansible_env.HOME }}/.gitignore"

- name: gpg sign is enabled
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: "true"

- name: neovim is core editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: nvim
