---

- name: git is installed
  become: "yes"
  zypper:
    name: git

- name: rebase on pull
  git_config:
    name: pull.rebase
    scope: global
    value: 'true'

- name: autostash on rebase
  git_config:
    name: rebase.autostash
    scope: global
    value: 'true'

- name: color ui is enabled
  git_config:
    name: color.ui
    scope: global
    value: 'true'

- name: simple push
  git_config:
    name: push.default
    scope: global
    value: simple

- name: dont prompt mergetool
  git_config:
    name: mergetool.prompt
    scope: global
    value: "false"

- name: dont prompt difftool
  git_config:
    name: difftool.prompt
    scope: global
    value: "false"

- name: cherry-pick alias
  git_config:
    name: alias.cp
    scope: global
    value: cherry-pick

- name: global git ignore file
  git_config:
    name: core.excludesfile
    scope: global
    value: "{{ ansible_env.HOME }}/.gitignore"

- name: gpg sign is enabled
  git_config:
    name: commit.gpgsign
    scope: global
    value: "true"

- name: neovim is core editor
  git_config:
    name: core.editor
    scope: global
    value: nvim
