- name: Install Vundle
  git:
    repo: https://github.com/MichaelAquilina/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    update: no

- name: mkdir vim
  file:
    path: ~/.vim/colors
    state: directory

- name: Install Vim Molokai Theme
  get_url:
    url: https://raw.githubusercontent.com/MichaelAquilina/molokai/master/colors/molokai.vim
    dest: ~/.vim/colors/molokai.vim

- name: ~/.vimrc
  file:
    state: link
    force: yes
    src: "{{ ansible_env.PWD }}/roles/vim/files/vimrc"
    dest: "~/.vimrc"
